In [2]:
import pandas as pd
import numpy as np

# 通过ndarray构建DataFrame
t = pd.DataFrame(np.arange(12).reshape((3,4))) #默认索引是0-2
print(t)
print('-'*50)


   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
--------------------------------------------------


In [3]:
array = np.random.randn(5,4)
print(array)
print('-'*50)
df_obj = pd.DataFrame(array)
print(df_obj.head()) #默认显示前5行

[[-1.55578021 -0.67971377 -0.16865584  0.03785596]
 [ 0.38332086 -0.37438687 -0.14047802  0.22504158]
 [ 0.9654522   0.56305695 -1.09878625  0.1705258 ]
 [ 0.75073534 -1.23954841 -1.4064546  -0.14563121]
 [ 0.4316606   1.88561855  0.56137432  1.17341387]]
--------------------------------------------------
          0         1         2         3
0 -1.555780 -0.679714 -0.168656  0.037856
1  0.383321 -0.374387 -0.140478  0.225042
2  0.965452  0.563057 -1.098786  0.170526
3  0.750735 -1.239548 -1.406455 -0.145631
4  0.431661  1.885619  0.561374  1.173414


In [4]:
t.loc[0] #单独把某一行取出来,类型是series

0    0
1    1
2    2
3    3
Name: 0, dtype: int64

In [5]:
# 列表套字典  变df
d2 =[{"name" : "xiaohong" ,"age" :32,"tel" :10010},
     { "name": "xiaogang" ,"tel": 10000} ,
     {"name":"xiaowang" ,"age":22}]
df6=pd.DataFrame(d2)
print(df6) #缺失值会用NaN填充
print(type(df6.values)) #ndarray

       name   age      tel
0  xiaohong  32.0  10010.0
1  xiaogang   NaN  10000.0
2  xiaowang  22.0      NaN
<class 'numpy.ndarray'>


In [6]:
pd.Series(1, index=list(range(3,7)),dtype='float32')

3    1.0
4    1.0
5    1.0
6    1.0
dtype: float32

In [7]:
#df中不同列可以是不同的数据类型,同一列必须是一个数据类型
import pandas as pd
import numpy as np
dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([1,2,3,4],dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'wangdao' }
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2)


   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao


In [8]:
print('-'*50)
print(df_obj2.index) #行索引,重点
#补课改变
# df_obj2.index[0]=2  不可以单独修改某个索引值
print(df_obj2.columns) #列索引，重点
df_obj2.dtypes #每一列的数据类型，重点

--------------------------------------------------
Index([0, 1, 2, 3], dtype='int64')
Index(['A', 'B', 'C', 'D', 'E', 'F'], dtype='str')


A             int64
B    datetime64[us]
C           float32
D             int32
E               str
F               str
dtype: object

In [9]:
# 感受日期,初始化df，设置行索引，列索引
dates = pd.date_range('20130101', periods=6) #默认freq='D'，即天
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
print(df)
print('-'*50)
print(df.index)


                   A         B         C         D
2013-01-01 -0.537791  1.514253 -1.014612  0.998491
2013-01-02  0.634610  1.618191 -1.981646  0.599803
2013-01-03 -1.455825 -1.526266  0.368726  0.696363
2013-01-04  0.868005 -0.461971 -1.039348 -0.089695
2013-01-05 -0.412920  1.445588 -0.456046  0.593317
2013-01-06 -0.420495 -0.766416  0.218146  0.510430
--------------------------------------------------
DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')


In [10]:
#取数据
print(df_obj2)
print('-'*50)
print(type(df_obj2))
print('-'*50)
#pd中使用索引名来取某一行，或者列
print(df_obj2['B'])
print('-'*50)
#把df的某一列取出来是series
print(type(df_obj2['B']))

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
--------------------------------------------------
<class 'pandas.DataFrame'>
--------------------------------------------------
0   2019-09-26
1   2019-09-26
2   2019-09-26
3   2019-09-26
Name: B, dtype: datetime64[us]
--------------------------------------------------
<class 'pandas.Series'>


In [11]:
#增加列数据，列名是自定义的
df_obj2['G'] = df_obj2['D'] + 4
print(df_obj2.head())

   A          B    C  D       E        F  G
0  1 2019-09-26  1.0  1  Python  wangdao  5
1  1 2019-09-26  1.0  2    Java  wangdao  6
2  1 2019-09-26  1.0  3     C++  wangdao  7
3  1 2019-09-26  1.0  4       C  wangdao  8


In [12]:
# 删除列
del(df_obj2['G'])
print(df_obj2.head())



   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
